/* Mock mirgation tables, 
in this library the two ones are:
- IC_CL.Z_DIM_POL_MIG_CNTRL 
- IC_CL.Z_FACT_POL_MIG_ERR_TRAN 
*/
libname IC_CLNXT ORACLE PATH='cldh01s.nsc.net'  USER= &UID PASSWORD= &Netezza_Auth SCHEMA='ic_clnxt';

libname STATELOB "/sasdata-fsx/SASApp/Commercial/Analytics_Team/CLT Mock Migration/MatthewMeyer/" ;
run;

proc sql;
CREATE TABLE MAIN_TEST as
SELECT
	POL_REN_CNTRL_ID,
	LEGACY_ACCT_NO,
	LEGACY_POL_NO,
	datepart(LEGACY_POL_EFF_DT) as LEGACY_POL_EFF_DT FORMAT=DATE9.,
	datepart(LEGACY_POL_EXP_DT) as LEGACY_POL_EXP_DT FORMAT=DATE9.,
	MIG_PROC_CD,
	PC_ACCT_NO,
	PC_POL_NO,
	ETL_ADD_DTS,
	SOURCE_SYSTEM,
	MIG_UPDT_DTS,
	AWD_TASK_POL_IND,
	BATCH_ID,
	MIG_PROC_TXT
FROM IC_CLNXT.Z_DIM_POL_MIG_CNTRL
ORDER BY POL_REN_CNTRL_ID;
QUIT;



data MAIN_TEST;
set MAIN_TEST;
LEGACY_POL_NO = compress(LEGACY_POL_NO);
PC_POL_NO = compress(PC_POL_NO);
run;


proc sql;
CREATE TABLE MAIN_JOINED as 
SELECT
	POL_REN_CNTRL_ID as POLICY_RENEWAL_CONTROL_ID,
	LEGACY_ACCT_NO as SOURCE_ACCOUNT_NUMBER,
	LEGACY_POL_NO,
	LEGACY_POL_EFF_DT,
	LEGACY_POL_EXP_DT as POL_EXPIR,
	MIG_PROC_CD as MIG_PROCESS_CDE,
	PC_ACCT_NO as CLT_ACCOUNT_NUMBER,
	PC_POL_NO as CLT_POLICY_NUMBER,
	ETL_ADD_DTS as INITIAL_L,
	SOURCE_SYSTEM as SOURCE_SYSTEM_TXT,
	MIG_UPDT_DTS as MIG_UPDT_TS,
	AWD_TASK_POL_IND as AWD_TASK_PLCY_IND,
	BATCH_ID,
	LOB,
	primary_state_cde as State,
	MIG_PROC_TXT
FROM MAIN_TEST left join STATELOB.COMBINED_HVPCIO
on MAIN_TEST.LEGACY_POL_NO = COMBINED_HVPCIO.Policy and MAIN_TEST.LEGACY_POL_EFF_DT = COMBINED_HVPCIO.POL_EFFECTIVE_DT;   
QUIT;

data MAIN_JOINED;
set MAIN_JOINED;
SOURCE_POLICY_NUMBER = LEGACY_POL_NO;
DROP LEGACY_POL_NO;
DROP LEGACY_POL_EFF_DT;
run;

proc sql;
CREATE TABLE FINAL AS
SELECT 
	POLICY_RENEWAL_CONTROL_ID,
	SOURCE_ACCOUNT_NUMBER,
	SOURCE_POLICY_NUMBER,
	POL_EXPIR,
	MIG_PROCESS_CDE,
	CLT_ACCOUNT_NUMBER,
	CLT_POLICY_NUMBER,
	INITIAL_L,
	SOURCE_SYSTEM_TXT,
	MIG_UPDT_TS,
	AWD_TASK_PLCY_IND,
	BATCH_ID,
	LOB,
	State,
	MIG_PROC_TXT
FROM MAIN_JOINED;
QUIT;

/* Add something here to export it */

proc sql;
SELECT *
FROM FINAL
WHERE LOB = "BA";
QUIT;
